apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-generator
  template:
    metadata:
      labels:
        app: pdf-generator
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: gotenberg
          image: 'gotenberg/gotenberg:7'
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 1280Mi
              cpu: '0.5'
            requests:
              memory: 500Mi
              cpu: '0.5'
          livenessProbe:
            httpGet:
              path: '/health'
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: '/health'
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
        - name: gotenberg-reverse-proxy
          image: 'gotenberg-reverse-proxy:latest'
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: '0.5'
            requests:
              memory: 128Mi
              cpu: '0.5'
          livenessProbe:
            httpGet:
              path: '/health'
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: '/health'
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          env:
            - name: 'ForwardSettings__GotenbergInstanceUrl'
              value: 'pdf-generator.default.svc.cluster.local'